version: "3.8"

services:
  mariadb:
    image: mariadb:11.3
    container_name: demo-mariadb
    environment:
      MARIADB_DATABASE: demo
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
